name: ppl_app
description: Premier Project League - Flutter App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.1.0
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  go_router: ^13.0.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.6
  email_validator: ^2.1.17
  google_sign_in: ^6.2.1
  file_picker: ^8.0.6+1
  image_picker: ^1.0.7
  video_player: ^2.8.2
  chewie: ^1.7.5
  intl: ^0.19.0
  url_launcher: ^6.2.3
  animations: ^2.0.11
  lottie: ^3.0.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  http_parser: ^4.0.2
  mime: ^1.0.5
  app_links: ^6.3.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/